services:
  # Backend Web Service
  - type: web
    name: autimilezzz-backend
    runtime: node
    region: oregon
    branch: main
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
    healthCheckPath: /

  # Frontend Static Site
  - type: web
    name: autimilezzz-frontend
    runtime: static
    branch: main
    rootDir: frontend
    buildCommand: echo "No build needed"
    staticPublishPath: .
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=0, must-revalidate
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
